[tool.poetry]
name = "imgapp"
version = "0.1.0"
description = ""
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]
packages = [
    { include = "imgapp" },
    { include = "imgapp/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
Flask = "^2.1.3"
Pillow = "^9.2.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
imgapp = "imgapp:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
